// client/www/components/intern/docs-feedback/auth.tsx
'use client';

import React, { useState } from 'react';
import db from '@/lib/intern/docs-feedback/db';

export function AuthGate({ children }: { children: React.ReactNode }) {
  const { user, isLoading, error } = db.useAuth();

  if (isLoading)
    return (
      <div className="flex min-h-screen items-center justify-center">
        Loading...
      </div>
    );
  if (error)
    return <div className="p-4 text-red-500">Auth error: {error.message}</div>;
  if (!user) return <Login />;

  return <>{children}</>;
}

function Login() {
  const [sentEmail, setSentEmail] = useState('');

  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-50">
      <div className="w-full max-w-md rounded-lg bg-white p-8 shadow-md">
        {!sentEmail ? (
          <EmailStep onSendEmail={setSentEmail} />
        ) : (
          <CodeStep sentEmail={sentEmail} />
        )}
      </div>
    </div>
  );
}

function EmailStep({ onSendEmail }: { onSendEmail: (email: string) => void }) {
  const inputRef = React.useRef<HTMLInputElement>(null);

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const inputEl = inputRef.current!;
    const email = inputEl.value;
    onSendEmail(email);
    db.auth.sendMagicCode({ email }).catch((err) => {
      alert('Error: ' + err.body?.message);
      onSendEmail('');
    });
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div>
        <h2 className="mb-2 text-2xl font-bold text-gray-900">
          Feedback Analytics
        </h2>
        <p className="text-gray-600">
          Enter your email to access the analytics dashboard
        </p>
      </div>

      <div>
        <label
          htmlFor="email"
          className="mb-2 block text-sm font-medium text-gray-700"
        >
          Email address
        </label>
        <input
          ref={inputRef}
          id="email"
          type="email"
          required
          autoFocus
          className="w-full rounded-md border border-gray-300 px-3 py-2 focus:border-transparent focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="Enter your email"
        />
      </div>

      <button
        type="submit"
        className="flex w-full justify-center rounded-md border border-transparent bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
      >
        Send Magic Code
      </button>
    </form>
  );
}

function CodeStep({ sentEmail }: { sentEmail: string }) {
  const inputRef = React.useRef<HTMLInputElement>(null);

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const inputEl = inputRef.current!;
    const code = inputEl.value;
    db.auth.signInWithMagicCode({ email: sentEmail, code }).catch((err) => {
      inputEl.value = '';
      alert('Error: ' + err.body?.message);
    });
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div>
        <h2 className="mb-2 text-2xl font-bold text-gray-900">
          Enter verification code
        </h2>
        <p className="text-gray-600">
          We sent a verification code to <strong>{sentEmail}</strong>. Check
          your email and enter the code below.
        </p>
      </div>

      <div>
        <label
          htmlFor="code"
          className="mb-2 block text-sm font-medium text-gray-700"
        >
          Verification code
        </label>
        <input
          ref={inputRef}
          id="code"
          type="text"
          required
          autoFocus
          className="w-full rounded-md border border-gray-300 px-3 py-2 focus:border-transparent focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="Enter verification code"
        />
      </div>

      <button
        type="submit"
        className="flex w-full justify-center rounded-md border border-transparent bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
      >
        Verify Code
      </button>
    </form>
  );
}

// client/sandbox/sveltekit/src/routes/auth/+page.svelte
<script lang="ts">
  import { SignedIn, SignedOut } from '@instantdb/svelte';
  import { dbState } from '$lib/db.svelte';

  let email = $state('');
  let code = $state('');
  let sentTo = $state('');
</script>

{#if dbState.isLoading}
  <div class="p-8 flex justify-center">Creating ephemeral app...</div>
{:else if dbState.error}
  <div class="p-8 text-red-500">Error: {dbState.error}</div>
{:else}
  {@const db = dbState.db!}
  <div class="p-8 max-w-md mx-auto flex flex-col gap-4">
    <h1 class="text-2xl text-[#F54A00] tracking-wide">Auth Components Test</h1>

    <SignedOut {db}>
      <div class="bg-white rounded-lg p-6 border border-neutral-200 shadow flex flex-col gap-4">
        <h2 class="text-lg font-semibold">Signed Out</h2>
        <p class="text-sm text-neutral-500">
          This content is rendered by the SignedOut component.
        </p>
        {#if !sentTo}
          <form
            class="flex flex-col gap-2"
            onsubmit={(e) => {
              e.preventDefault();
              if (!email) return;
              db.auth.sendMagicCode({ email }).then(() => { sentTo = email; });
            }}
          >
            <input
              bind:value={email}
              type="email"
              placeholder="Enter your email"
              class="border border-neutral-300 rounded px-3 py-2 outline-none"
            />
            <button type="submit" class="bg-[#F54A00] text-white rounded px-3 py-2">
              Send Magic Code
            </button>
          </form>
        {:else}
          <form
            class="flex flex-col gap-2"
            onsubmit={(e) => {
              e.preventDefault();
              if (!code) return;
              db.auth.signInWithMagicCode({ email: sentTo, code }).catch(() => {
                code = '';
              });
            }}
          >
            <p class="text-sm">Code sent to {sentTo}</p>
            <input
              bind:value={code}
              type="text"
              placeholder="Enter code"
              class="border border-neutral-300 rounded px-3 py-2 outline-none"
            />
            <button type="submit" class="bg-[#F54A00] text-white rounded px-3 py-2">
              Verify Code
            </button>
          </form>
        {/if}
      </div>
    </SignedOut>

    <SignedIn {db}>
      <div class="bg-white rounded-lg p-6 border border-neutral-200 shadow flex flex-col gap-4">
        <h2 class="text-lg font-semibold">Signed In</h2>
        <p class="text-sm text-neutral-500">
          This content is rendered by the SignedIn component.
        </p>
        <button
          class="bg-neutral-200 rounded px-3 py-2 hover:bg-neutral-300"
          onclick={() => db.auth.signOut()}
        >
          Sign Out
        </button>
      </div>
    </SignedIn>
  </div>
{/if}
