// client/sandbox/sveltekit/src/routes/+page.svelte
<script lang="ts">
  import { id, type InstaQLEntity } from '@instantdb/svelte';
  import { dbState, type AppSchema } from '$lib/db.svelte';

  type Todo = InstaQLEntity<AppSchema, 'todos'>;

  let text = $state('');
</script>

{#if dbState.isLoading}
  <div class="p-8 flex justify-center">Creating ephemeral app...</div>
{:else if dbState.error}
  <div class="p-8 text-red-500">Error: {dbState.error}</div>
{:else}
  {@const db = dbState.db!}
  {@const query = db.useQuery({ todos: {} })}
  <div class="p-8 grid grid-cols-2 items-start gap-2">
    {@render welcome()}
    {@render todoApp(db, query)}
  </div>
{/if}

{#snippet welcome()}
  <div class="bg-white p-6 rounded-lg border border-neutral-200 shadow flex justify-center flex-col gap-2">
    <h2 class="tracking-wide text-[#F54A00] text-2xl text-center">
      SvelteKit + Instant DB
    </h2>
    <div class="grid grid-cols-1 md:grid-cols-2 grow gap-2">
      <a
        href="https://svelte.dev/docs/svelte"
        target="_blank"
        rel="noopener noreferrer"
        class="border hover:bg-neutral-100 py-8 shadow flex flex-col gap-2 items-center justify-center font-semibold border-neutral-200 rounded"
      >
        <img src="https://svelte.dev/svelte-logo.svg" width={34} alt="Svelte logo" />
        Svelte Docs
      </a>
      <a
        target="_blank"
        href="https://www.instantdb.com/docs"
        rel="noopener noreferrer"
        class="border shadow flex flex-col py-8 gap-2 hover:bg-neutral-100 items-center justify-center font-semibold border-neutral-200 rounded"
      >
        <img src="https://www.instantdb.com/img/icon/logo-512.svg" width={34} alt="InstantDB logo" />
        Instant Docs
      </a>
    </div>
  </div>
{/snippet}

{#snippet todoApp(db: any, query: any)}
  <div class="bg-white rounded-lg p-6 border border-neutral-200 shadow flex flex-col">
    <h2 class="tracking-wide text-[#F54A00] text-2xl">Todos</h2>
    <div class="text-xs pb-4">
      Open another tab to see todos update in realtime!
    </div>
    {#if query.isLoading}
      <div>Loading...</div>
    {:else if query.error}
      <div class="text-red-500">Error: {query.error.message}</div>
    {:else}
      {@const todos = query.data?.todos ?? []}
      <div class="border rounded border-neutral-300">
        {@render todoForm(db)}
        {@render todoList(db, todos)}
        {@render actionBar(db, todos)}
      </div>
    {/if}
  </div>
{/snippet}

{#snippet todoForm(db: any)}
  <div class="flex items-center h-10 border-neutral-300">
    <form
      class="flex-1 h-full"
      onsubmit={(e) => {
        e.preventDefault();
        if (!text) return;
        db.transact(db.tx.todos[id()].update({ text, done: false, createdAt: Date.now() }));
        text = '';
      }}
    >
      <input
        bind:value={text}
        class="w-full h-full placeholder-neutral-300 px-2 outline-none bg-transparent"
        autofocus
        placeholder="What needs to be done?"
        type="text"
      />
    </form>
  </div>
{/snippet}

{#snippet todoList(db: any, todos: Todo[])}
  <div class="divide-y divide-neutral-300">
    {#each todos as todo (todo.id)}
      <div class="flex items-center h-10">
        <div class="h-full px-2 flex items-center justify-center">
          <div class="w-5 h-5 flex items-center justify-center">
            <input
              type="checkbox"
              class="cursor-pointer"
              checked={todo.done}
              onchange={() => db.transact(db.tx.todos[todo.id].update({ done: !todo.done }))}
            />
          </div>
        </div>
        <div class="flex-1 px-2 overflow-hidden flex items-center">
          <span class:line-through={todo.done}>{todo.text}</span>
        </div>
        <button
          class="h-full px-2 flex items-center justify-center text-neutral-300 hover:text-neutral-500"
          onclick={() => db.transact(db.tx.todos[todo.id].delete())}
        >
          X
        </button>
      </div>
    {/each}
  </div>
{/snippet}

{#snippet actionBar(db: any, todos: Todo[])}
  <div class="flex justify-between items-center h-10 px-2 text-xs border-t border-neutral-300">
    <div>
      Remaining todos: {todos.filter((t: Todo) => !t.done).length}
    </div>
    <button
      class="text-neutral-300 hover:text-neutral-500"
      onclick={() => {
        const completed = todos.filter((t: Todo) => t.done);
        if (completed.length) db.transact(completed.map((t: Todo) => db.tx.todos[t.id].delete()));
      }}
    >
      Delete Completed
    </button>
  </div>
{/snippet}

// examples/tanstack-start-with-tanstack-query/src/routes/index.tsx
import { AppSchema } from "@/instant.schema";
import { db } from "@/lib/db";
import { id, InstaQLEntity } from "@instantdb/react";
import { getRequest } from "@tanstack/react-start/server";

import { createFileRoute, redirect } from "@tanstack/react-router";
import { createMiddleware, createServerFn } from "@tanstack/react-start";
import { adminDb } from "@/lib/adminDb";
import { useInstantSuspenseQuery } from "@/lib/instantQuery";
import { useSuspenseQuery } from "@tanstack/react-query";

const instantUserMiddleware = createMiddleware().server(async ({ next }) => {
  const request = getRequest();
  // Gets user from cookie sync and validates refresh token
  const user = await adminDb.auth.getUserFromRequest(request);
  return next({
    context: { user },
  });
});

// Mimick cases where we want to use the Instant user to access secure data
// outside of the Instant database.
const getSecretData = createServerFn()
  .middleware([instantUserMiddleware])
  .handler(async ({ context }) => {
    if (!context.user) {
      throw new Error("Unauthorized");
    }

    // Free to use the Instant Admin DB or 3rd party server-side services.

    return {
      secretMessage:
        "This is a secret message returned from createServerFn. Only authenticated users can see this.",
    };
  });

export const Route = createFileRoute("/")({
  component: App,
  loader: async ({ context }) => {
    const user = await context.getUser();
    if (!user) {
      throw redirect({
        to: "/login",
      });
    }

    await context.preloadQuery({
      todos: {},
    });

    await context.queryClient.ensureQueryData({
      queryKey: ["secret"],
      queryFn: getSecretData,
    });
  },
  ssr: true,
  wrapInSuspense: true,
});

type Todo = InstaQLEntity<AppSchema, "todos">;

function App() {
  // Read Data
  const { data } = useInstantSuspenseQuery({ todos: {} });

  const todos = data.todos;
  return (
    <div className="p-8 grid-cols-2 items-start gap-2 grid">
      <div className="flex flex-col gap-2">
        <Welcome />
        <SecretData />
      </div>
      <div className="bg-white rounded-lg p-6 border border-neutral-200 shadow flex flex-col">
        <h2 className="tracking-wide text-[#F54A00] text-2xl">Todos</h2>
        <div className="text-xs pb-4">
          Open another tab to see todos update in realtime!
        </div>
        <div className="border rounded border-neutral-300">
          <TodoForm />
          <TodoList todos={todos} />
          <ActionBar todos={todos} />
        </div>
      </div>
    </div>
  );
}

// Write Data
// ---------
function addTodo(text: string) {
  db.transact(
    db.tx.todos[id()].update({
      text,
      done: false,
      createdAt: Date.now(),
    }),
  );
}

function deleteTodo(todo: Todo) {
  db.transact(db.tx.todos[todo.id].delete());
}

function toggleDone(todo: Todo) {
  db.transact(db.tx.todos[todo.id].update({ done: !todo.done }));
}

function deleteCompleted(todos: Todo[]) {
  const completed = todos.filter((todo) => todo.done);
  if (completed.length === 0) return;
  const txs = completed.map((todo) => db.tx.todos[todo.id].delete());
  db.transact(txs);
}

function TodoForm() {
  return (
    <div className="flex items-center h-10 border-neutral-300">
      <form
        className="flex-1 h-full"
        onSubmit={(e) => {
          e.preventDefault();
          const input = e.currentTarget.input as HTMLInputElement;
          addTodo(input.value);
          input.value = "";
        }}
      >
        <input
          className="w-full h-full px-2 outline-none bg-transparent"
          autoFocus
          placeholder="What needs to be done?"
          type="text"
          name="input"
        />
      </form>
    </div>
  );
}

function TodoList({ todos }: { todos: Todo[] }) {
  return (
    <div className="divide-y divide-neutral-300">
      {todos.map((todo) => (
        <div key={todo.id} className="flex items-center h-10">
          <div className="h-full px-2 flex items-center justify-center">
            <div className="w-5 h-5 flex items-center justify-center">
              <input
                type="checkbox"
                className="cursor-pointer"
                checked={todo.done}
                onChange={() => toggleDone(todo)}
              />
            </div>
          </div>
          <div className="flex-1 px-2 overflow-hidden flex items-center">
            {todo.done ? (
              <span className="line-through">{todo.text}</span>
            ) : (
              <span>{todo.text}</span>
            )}
          </div>
          <button
            className="h-full px-2 flex items-center justify-center text-neutral-300 hover:text-neutral-500"
            onClick={() => deleteTodo(todo)}
          >
            X
          </button>
        </div>
      ))}
    </div>
  );
}

function ActionBar({ todos }: { todos: Todo[] }) {
  return (
    <div className="flex justify-between items-center h-10 px-2 text-xs border-t border-neutral-300">
      <div>Remaining todos: {todos.filter((todo) => !todo.done).length}</div>
      <button
        className=" text-neutral-300 hover:text-neutral-500"
        onClick={() => deleteCompleted(todos)}
      >
        Delete Completed
      </button>
    </div>
  );
}

export function Welcome() {
  return (
    <div className="bg-white p-6 rounded-lg border border-neutral-200 shadow flex  justify-center flex-col gap-2">
      <h2 className="tracking-wide text-[#F54A00] text-2xl text-center">
        Tanstack Start + Instant DB
      </h2>
      <div className="grid grid-cols-1 md:grid-cols-2 grow gap-2">
        <a
          href="https://tanstack.com/start/latest/docs/framework/react/overview"
          target="_blank"
          rel="noopener noreferrer"
          className="border hover:bg-neutral-100 py-8 shadow flex flex-col gap-2 items-center justify-center font-semibold border-neutral-200 rounded"
        >
          <img
            src="https://tanstack.com/images/logos/logo-color-600.png"
            width={34}
          ></img>
          Tanstack Start Docs
        </a>
        <a
          target="_blank"
          href="https://www.instantdb.com/docs"
          rel="noopener noreferrer"
          className="border hover:bg-neutral-100 py-8 shadow flex flex-col gap-2 items-center justify-center font-semibold border-neutral-200 rounded"
        >
          <img
            src="https://www.instantdb.com/img/icon/logo-512.svg"
            width={34}
          ></img>
          Instant Docs
        </a>
      </div>
    </div>
  );
}

const SecretData = () => {
  const { data: secret } = useSuspenseQuery({
    queryKey: ["secret"],
    queryFn: getSecretData,
  });

  return (
    <div className="bg-white p-6 rounded-lg border border-neutral-200 shadow flex  justify-center flex-col gap-2">
      <div>Secret Message:</div>
      <div>{secret?.secretMessage}</div>
    </div>
  );
};
