// examples/solidjs-vite-advanced/src/components/Login.tsx
import { type Component, createSignal, Show } from "solid-js";
import { db } from "../lib/db";

const Login: Component = () => {
  const [email, setEmail] = createSignal("");
  const [code, setCode] = createSignal("");
  const [sentTo, setSentTo] = createSignal("");
  const [error, setError] = createSignal("");

  const handleSendCode = async (e: Event) => {
    e.preventDefault();
    setError("");
    try {
      await db.auth.sendMagicCode({ email: email() });
      setSentTo(email());
    } catch (err: any) {
      setError(err.body?.message || err.message);
    }
  };

  const handleVerifyCode = async (e: Event) => {
    e.preventDefault();
    setError("");
    try {
      await db.auth.signInWithMagicCode({
        email: sentTo(),
        code: code(),
      });
    } catch (err: any) {
      setError(err.body?.message || err.message);
    }
  };

  return (
    <div class="flex items-center justify-center min-h-screen">
      <div class="bg-white rounded-lg shadow p-6 w-full max-w-sm space-y-4">
        <h2 class="text-lg font-bold text-center">Sign in</h2>

        <Show when={error()}>
          <p class="text-red-500 text-sm">{error()}</p>
        </Show>

        <Show
          when={sentTo()}
          fallback={
            <form onSubmit={handleSendCode} class="space-y-3">
              <input
                type="email"
                placeholder="you@example.com"
                value={email()}
                onInput={(e) => setEmail(e.currentTarget.value)}
                class="w-full border rounded px-3 py-2 text-sm"
                required
              />
              <button
                type="submit"
                class="w-full bg-blue-600 text-white rounded px-3 py-2 text-sm hover:bg-blue-700 transition-colors"
              >
                Send magic code
              </button>
            </form>
          }
        >
          <form onSubmit={handleVerifyCode} class="space-y-3">
            <p class="text-sm text-gray-600">
              We sent a code to <strong>{sentTo()}</strong>
            </p>
            <input
              type="text"
              placeholder="Enter code"
              value={code()}
              onInput={(e) => setCode(e.currentTarget.value)}
              class="w-full border rounded px-3 py-2 text-sm"
              required
            />
            <button
              type="submit"
              class="w-full bg-blue-600 text-white rounded px-3 py-2 text-sm hover:bg-blue-700 transition-colors"
            >
              Verify code
            </button>
            <button
              type="button"
              class="w-full text-sm text-gray-500 hover:text-gray-700"
              onClick={() => {
                setSentTo("");
                setCode("");
              }}
            >
              Use a different email
            </button>
          </form>
        </Show>
      </div>
    </div>
  );
};

export default Login;

// examples/tanstack-start-with-tanstack-query/src/routes/login.tsx
import { db } from "@/lib/db";
import { createFileRoute, redirect } from "@tanstack/react-router";
import { useState } from "react";

export const Route = createFileRoute("/login")({
  component: RouteComponent,
  ssr: true,
  loader: async ({ context }) => {
    const user = await context.getUser();
    if (user) {
      throw redirect({
        to: "/",
      });
    }
  },
});

function RouteComponent() {
  const [stage, setStage] = useState<"email" | "code">("email");
  const [emailInput, setEmailInput] = useState("");
  const [codeInput, setCodeInput] = useState("");

  const sendEmail = async () => {
    await db.auth.sendMagicCode({ email: emailInput });
    setStage("code");
  };

  const loginWithCode = () => {
    db.auth.signInWithMagicCode({
      email: emailInput,
      code: codeInput,
    });
  };

  const goBack = () => {
    setStage("email");
    setCodeInput("");
  };

  return (
    <div className="font-mono pt-24 flex justify-center items-center flex-col space-y-4">
      <h2 className="tracking-wide text-5xl text-gray-300">
        {stage === "email" ? "sign in" : "enter code"}
      </h2>
      <p className="text-xs text-gray-500">
        {stage === "email"
          ? "Enter your email to receive a magic code"
          : `We sent a code to ${emailInput}`}
      </p>
      <div className="border border-gray-300 max-w-xs w-full">
        {stage === "email" ? (
          <form
            className="flex items-center h-10"
            onSubmit={(e) => {
              e.preventDefault();
              sendEmail();
            }}
          >
            <input
              type="email"
              value={emailInput}
              onChange={(e) => setEmailInput(e.target.value)}
              placeholder="you@example.com"
              required
              autoFocus
              className="flex-1 h-full px-2 outline-none bg-transparent"
            />
            <button
              type="submit"
              disabled={!emailInput}
              className="h-full px-2 border-l border-gray-300 text-gray-300 hover:text-gray-500 disabled:hover:text-gray-300"
            >
              Send
            </button>
          </form>
        ) : (
          <>
            <form
              className="flex items-center h-10 border-b border-gray-300"
              onSubmit={(e) => {
                e.preventDefault();
                loginWithCode();
              }}
            >
              <input
                type="text"
                value={codeInput}
                onChange={(e) => setCodeInput(e.target.value)}
                placeholder="Enter your code"
                required
                autoFocus
                className="flex-1 h-full px-2 outline-none bg-transparent"
              />
              <button
                type="submit"
                disabled={!codeInput}
                className="h-full px-2 border-l border-gray-300 text-gray-300 hover:text-gray-500 disabled:hover:text-gray-300"
              >
                Submit
              </button>
            </form>
            <div className="flex justify-center items-center h-10 px-2 text-xs">
              <button
                type="button"
                onClick={goBack}
                className="text-gray-300 hover:text-gray-500"
              >
                Use a different email
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
