// client/sandbox/sveltekit/src/routes/infinite-scroll/+page.svelte
<script lang="ts">
  import { id, tx } from '@instantdb/svelte';
  import { dbState, resetEphemeralApp } from '$lib/db.svelte';

  const pageSize = 4;
  let writeQueue: Promise<unknown> = Promise.resolve();
  let numberInput = $state('');

  function enqueue(work: () => Promise<unknown>) {
    writeQueue = writeQueue.then(work, work);
  }

  function addNumberItem(db: any, value: number) {
    enqueue(() => db.transact([tx.items[id()].update({ value })]));
  }

  function submitNumber(db: any) {
    const parsed = Number(numberInput);
    if (!Number.isFinite(parsed)) return;
    addNumberItem(db, parsed);
    numberInput = '';
  }

  function addNewLowest(db: any) {
    enqueue(async () => {
      const snapshot = await db.queryOnce({ items: {} });
      const existing = snapshot.data.items || [];
      const minValue = existing.reduce(
        (min: number, item: { value: number }) => Math.min(min, item.value),
        Number.POSITIVE_INFINITY,
      );
      const nextValue = Number.isFinite(minValue) ? minValue - 1 : -1;
      await db.transact([tx.items[id()].update({ value: nextValue })]);
    });
  }

  function addZero(db: any) {
    addNumberItem(db, 0);
  }

  function addNewHighest(db: any) {
    enqueue(async () => {
      const snapshot = await db.queryOnce({ items: {} });
      const existing = snapshot.data.items || [];
      const maxValue = existing.reduce(
        (max: number, item: { value: number }) => Math.max(max, item.value),
        Number.NEGATIVE_INFINITY,
      );
      const nextValue = Number.isFinite(maxValue) ? maxValue + 1 : 1;
      await db.transact([tx.items[id()].update({ value: nextValue })]);
    });
  }

  async function deleteAll(db: any) {
    const snapshot = await db.queryOnce({ items: {} });
    const existing = snapshot.data.items || [];
    if (existing.length === 0) return;
    await db.transact(
      existing.map((item: { id: string }) => tx.items[item.id].delete()),
    );
  }
</script>

{#if dbState.isLoading}
  <div class="p-8 flex justify-center">Creating ephemeral app...</div>
{:else if dbState.error}
  <div class="p-8 text-red-500">Error: {dbState.error}</div>
{:else}
  {@const db = dbState.db!}
  {@const scrollResult = db.useInfiniteQuery({
    items: {
      $: { limit: pageSize, order: { value: 'asc' } },
    },
  })}
  {@const allNumbersResult = db.useQuery({ items: {} })}
  {@const numberLineValues = [...(allNumbersResult.data?.items || [])].sort(
    (a, b) => a.value - b.value,
  )}
  {@const loadedValues = (scrollResult.data?.items || []).map((i) => i.value)}

  <div class="p-4">
    <div class="flex flex-wrap items-center gap-2">
      <input
        class="border border-gray-400 p-2"
        type="number"
        bind:value={numberInput}
        onkeydown={(e) => {
          if (e.key === 'Enter') submitNumber(db);
        }}
        placeholder="Type a number"
      />
      <button class="bg-black p-2 text-white" onclick={() => submitNumber(db)}>
        Add number
      </button>
      <button class="bg-black p-2 text-white" onclick={() => addNewLowest(db)}>
        Add new lowest
      </button>
      <button class="bg-black p-2 text-white" onclick={() => addZero(db)}>
        Add zero
      </button>
      <button class="bg-black p-2 text-white" onclick={() => addNewHighest(db)}>
        Add new highest
      </button>
      <button class="bg-black p-2 text-white" onclick={() => deleteAll(db)}>
        Delete all
      </button>
      <button class="bg-black p-2 text-white" onclick={resetEphemeralApp}>
        Start over
      </button>
    </div>

    <button
      class="my-2 bg-black p-2 text-white disabled:opacity-50"
      disabled={!scrollResult.canLoadNextPage}
      onclick={() => scrollResult.loadNextPage()}
    >
      Load more
    </button>

    <div class="my-2 border border-gray-300 p-3">
      <h3 class="font-bold">Number line ({numberLineValues.length})</h3>
      {#if numberLineValues.length === 0}
        <div class="mt-2 text-sm">No numbers yet.</div>
      {:else}
        <div class="mt-3 overflow-x-auto">
          <div class="min-w-max border-t-2 border-black px-4 pb-2">
            <div class="flex gap-6">
              {#each numberLineValues as item (item.id)}
                <div class="-mt-4 flex flex-col items-center">
                  <div class="h-4 w-px bg-black"></div>
                  <div class="mt-1 font-mono text-sm">{item.value}</div>
                </div>
              {/each}
            </div>
          </div>
        </div>
      {/if}
    </div>

    <div class="grid gap-2 md:grid-cols-2">
      <div class="border border-gray-300 bg-gray-100 p-3 text-xs">
        <h3 class="font-bold">Infinite Query Diagnostics</h3>
        <pre>canLoadNextPage: {String(scrollResult.canLoadNextPage)}</pre>
        <pre>isLoading: {String(scrollResult.isLoading)}</pre>
        <pre>loaded: {loadedValues.length}</pre>
      </div>

      <div class="border border-gray-300 p-3">
        <h3 class="font-bold">Loaded items ({loadedValues.length})</h3>
        {#if loadedValues.length === 0}
          <div>No items loaded yet.</div>
        {:else}
          {#each scrollResult.data?.items || [] as item (item.id)}
            <div class="font-mono text-sm">{item.value}</div>
          {/each}
        {/if}
      </div>
    </div>
  </div>
{/if}

// client/sandbox/solid-vite/src/pages/InfiniteScroll.tsx
import { Show, createMemo, createSignal } from 'solid-js';
import { id, tx } from '@instantdb/solidjs';
import { dbState, resetEphemeralApp, type DB } from '../lib/db';

const pageSize = 4;

const btnStyle = {
  margin: '8px',
  padding: '8px',
  background: 'black',
  color: 'white',
  border: 'none',
  cursor: 'pointer',
} as const;

function Demo({ db }: { db: DB }) {
  const [numberInput, setNumberInput] = createSignal('');
  let writeQueue: Promise<unknown> = Promise.resolve();

  const enqueue = (work: () => Promise<unknown>) => {
    writeQueue = writeQueue.then(work, work);
  };

  const scrollResult = db.useInfiniteQuery({
    items: {
      $: { limit: pageSize, order: { value: 'asc' } },
    },
  });
  const allNumbersResult = db.useQuery({ items: {} });

  const addNumberItem = (value: number) => {
    enqueue(() => db.transact([tx.items[id()].update({ value })]));
  };

  const submitNumber = () => {
    const parsed = Number(numberInput());
    if (!Number.isFinite(parsed)) return;
    addNumberItem(parsed);
    setNumberInput('');
  };

  const addNewLowest = () => {
    enqueue(async () => {
      const snapshot = await db.queryOnce({ items: {} });
      const existing = snapshot.data.items || [];
      const minValue = existing.reduce(
        (min, item) => Math.min(min, item.value),
        Number.POSITIVE_INFINITY,
      );
      const nextValue = Number.isFinite(minValue) ? minValue - 1 : -1;
      await db.transact([tx.items[id()].update({ value: nextValue })]);
    });
  };

  const addNewHighest = () => {
    enqueue(async () => {
      const snapshot = await db.queryOnce({ items: {} });
      const existing = snapshot.data.items || [];
      const maxValue = existing.reduce(
        (max, item) => Math.max(max, item.value),
        Number.NEGATIVE_INFINITY,
      );
      const nextValue = Number.isFinite(maxValue) ? maxValue + 1 : 1;
      await db.transact([tx.items[id()].update({ value: nextValue })]);
    });
  };

  const deleteAll = async () => {
    const snapshot = await db.queryOnce({ items: {} });
    const existing = snapshot.data.items || [];
    if (existing.length === 0) return;
    await db.transact(existing.map((item) => tx.items[item.id].delete()));
  };

  const numberLineValues = createMemo(() =>
    [...(allNumbersResult().data?.items || [])].sort(
      (a, b) => a.value - b.value,
    ),
  );
  const loadedValues = createMemo(() => scrollResult().data?.items || []);

  return (
    <div style={{ padding: '16px', 'font-family': 'sans-serif' }}>
      <div>
        <input
          style={{
            margin: '8px',
            padding: '8px',
            border: '1px solid #999',
          }}
          type="number"
          value={numberInput()}
          onInput={(e) => setNumberInput(e.currentTarget.value)}
          onKeyDown={(e) => {
            if (e.key === 'Enter') submitNumber();
          }}
          placeholder="Type a number"
        />
        <button style={btnStyle} onClick={submitNumber}>
          Add number
        </button>
        <button style={btnStyle} onClick={addNewLowest}>
          Add new lowest
        </button>
        <button style={btnStyle} onClick={() => addNumberItem(0)}>
          Add zero
        </button>
        <button style={btnStyle} onClick={addNewHighest}>
          Add new highest
        </button>
        <button style={btnStyle} onClick={deleteAll}>
          Delete all
        </button>
        <button style={btnStyle} onClick={resetEphemeralApp}>
          Start over
        </button>
      </div>

      <button
        style={{
          ...btnStyle,
          opacity: scrollResult().canLoadNextPage ? 1 : 0.5,
        }}
        disabled={!scrollResult().canLoadNextPage}
        onClick={() => scrollResult().loadNextPage()}
      >
        Load more
      </button>

      <div style={{ margin: '8px', padding: '12px', border: '1px solid #ccc' }}>
        <h3 style={{ 'font-weight': 'bold' }}>
          Number line ({numberLineValues().length})
        </h3>
        <Show
          when={numberLineValues().length > 0}
          fallback={
            <div style={{ 'margin-top': '8px', 'font-size': '14px' }}>
              No numbers yet.
            </div>
          }
        >
          <div style={{ 'margin-top': '12px', 'overflow-x': 'auto' }}>
            <div
              style={{
                'min-width': 'max-content',
                'border-top': '2px solid black',
                padding: '0 16px 8px',
              }}
            >
              <div style={{ display: 'flex', gap: '24px' }}>
                {numberLineValues().map((item) => (
                  <div
                    style={{
                      'margin-top': '-16px',
                      display: 'flex',
                      'flex-direction': 'column',
                      'align-items': 'center',
                    }}
                  >
                    <div
                      style={{
                        height: '16px',
                        width: '1px',
                        background: 'black',
                      }}
                    />
                    <div
                      style={{
                        'margin-top': '4px',
                        'font-family': 'monospace',
                        'font-size': '14px',
                      }}
                    >
                      {item.value}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </Show>
      </div>

      <div
        style={{
          display: 'grid',
          'grid-template-columns': '1fr 1fr',
          gap: '8px',
          margin: '8px',
        }}
      >
        <div
          style={{
            border: '1px solid #ccc',
            background: '#f5f5f5',
            padding: '12px',
            'font-size': '12px',
          }}
        >
          <h3 style={{ 'font-weight': 'bold' }}>Infinite Query Diagnostics</h3>
          <pre>canLoadNextPage: {String(scrollResult().canLoadNextPage)}</pre>
          <pre>isLoading: {String(scrollResult().isLoading)}</pre>
          <pre>loaded: {loadedValues().length}</pre>
        </div>
        <div style={{ border: '1px solid #ccc', padding: '12px' }}>
          <h3 style={{ 'font-weight': 'bold' }}>
            Loaded items ({loadedValues().length})
          </h3>
          <Show
            when={loadedValues().length > 0}
            fallback={<div>No items loaded yet.</div>}
          >
            {loadedValues().map((item) => (
              <div style={{ 'font-family': 'monospace', 'font-size': '14px' }}>
                {item.value}
              </div>
            ))}
          </Show>
        </div>
      </div>
    </div>
  );
}

export default function InfiniteScroll() {
  return (
    <Show
      when={!dbState().isLoading}
      fallback={
        <div
          style={{
            padding: '32px',
            display: 'flex',
            'justify-content': 'center',
          }}
        >
          Creating ephemeral app...
        </div>
      }
    >
      <Show
        when={!dbState().error}
        fallback={
          <div style={{ padding: '32px', color: 'red' }}>
            Error: {dbState().error}
          </div>
        }
      >
        <Demo db={dbState().db!} />
      </Show>
    </Show>
  );
}
