// client/sandbox/vue-vite/src/pages/TodoApp.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { id, type InstaQLEntity } from '@instantdb/vue';
import type { AppSchema, DB } from '../lib/db';

type Todo = InstaQLEntity<AppSchema, 'todos'>;

const props = defineProps<{ db: DB }>();

const text = ref('');

const { isLoading, error, data } = props.db.useQuery({ todos: {} });
const todos = computed(() => data.value?.todos ?? []);
const remaining = computed(() => todos.value.filter((t) => !t.done).length);

function addTodo() {
  const value = text.value.trim();
  if (!value) return;
  props.db.transact(
    props.db.tx.todos[id()].update({
      text: value,
      done: false,
      createdAt: Date.now(),
    }),
  );
  text.value = '';
}

function toggleDone(todo: Todo) {
  props.db.transact(props.db.tx.todos[todo.id].update({ done: !todo.done }));
}

function deleteTodo(todo: Todo) {
  props.db.transact(props.db.tx.todos[todo.id].delete());
}

function deleteCompleted() {
  const completed = todos.value.filter((t) => t.done);
  if (!completed.length) return;
  props.db.transact(completed.map((t) => props.db.tx.todos[t.id].delete()));
}
</script>

<template>
  <div class="p-8 grid grid-cols-2 items-start gap-2">
    <div
      class="bg-white p-6 rounded-lg border border-neutral-200 shadow flex flex-col gap-2"
    >
      <h2 class="tracking-wide text-[#F54A00] text-2xl text-center">
        Vue + Vite + Instant DB
      </h2>
    </div>

    <div
      class="bg-white rounded-lg p-6 border border-neutral-200 shadow flex flex-col"
    >
      <h2 class="tracking-wide text-[#F54A00] text-2xl">Todos</h2>
      <div class="text-xs pb-4">
        Open another tab to see todos update in realtime!
      </div>

      <div v-if="isLoading">Loading...</div>
      <div v-else-if="error" class="text-red-500">
        Error: {{ error.message }}
      </div>
      <div v-else class="border rounded border-neutral-300">
        <form
          class="flex items-center h-10 border-neutral-300"
          @submit.prevent="addTodo"
        >
          <input
            v-model="text"
            class="w-full h-full placeholder-neutral-300 px-2 outline-none bg-transparent"
            placeholder="What needs to be done?"
            type="text"
          />
        </form>

        <div class="divide-y divide-neutral-300">
          <div
            v-for="todo in todos"
            :key="todo.id"
            class="flex items-center h-10"
          >
            <div class="h-full px-2 flex items-center justify-center">
              <input
                type="checkbox"
                class="cursor-pointer w-5 h-5"
                :checked="todo.done"
                @change="toggleDone(todo)"
              />
            </div>
            <div class="flex-1 px-2 overflow-hidden flex items-center">
              <span :class="{ 'line-through': todo.done }">{{ todo.text }}</span>
            </div>
            <button
              class="h-full px-2 text-neutral-300 hover:text-neutral-500"
              @click="deleteTodo(todo)"
            >
              X
            </button>
          </div>
        </div>

        <div
          class="flex justify-between items-center h-10 px-2 text-xs border-t border-neutral-300"
        >
          <div>Remaining todos: {{ remaining }}</div>
          <button
            class="text-neutral-300 hover:text-neutral-500"
            @click="deleteCompleted"
          >
            Delete Completed
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// client/www/components/essays/architecture/TodoApp.tsx
import { useRef, useState } from 'react';
import { id } from '@instantdb/react';
import type {
  InstantReactWebDatabase,
  InstantUnknownSchema,
} from '@instantdb/react';

type InstantDB = InstantReactWebDatabase<InstantUnknownSchema>;

function CheckIcon() {
  return (
    <svg
      className="h-3 w-3 text-white"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={3}
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}

function ClipboardIcon() {
  return (
    <svg
      className="mb-3 h-12 w-12"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.5}
    >
      <path d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2" />
      <rect x="9" y="3" width="6" height="4" rx="1" />
    </svg>
  );
}

export default function TodoApp({ db }: { db: InstantDB }) {
  const [text, setText] = useState('');
  const inputRef = useRef<HTMLInputElement>(null);

  const { data, isLoading } = db.useQuery({
    todos: { $: { order: { createdAt: 'asc' } } },
  });

  const todos = data?.todos ?? [];

  const addTodo = () => {
    const trimmed = text.trim();
    if (!trimmed) return;
    db.transact(
      db.tx.todos[id()].update({
        text: trimmed,
        done: false,
        createdAt: Date.now(),
      }),
    );
    setText('');
    inputRef.current?.focus();
  };

  return (
    <div className="flex h-full flex-col bg-white">
      <div className="flex-1 overflow-y-auto px-5">
        {!isLoading && todos.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 text-gray-300">
            <ClipboardIcon />
            <span className="text-base">No todos yet</span>
          </div>
        ) : (
          todos.map((todo) => (
            <div
              key={todo.id}
              className="flex items-center gap-3 border-b border-gray-50 py-3"
            >
              <button
                onClick={() =>
                  db.transact(db.tx.todos[todo.id].update({ done: !todo.done }))
                }
                className={`flex h-[22px] w-[22px] flex-shrink-0 items-center justify-center rounded-full border-2 transition-colors ${
                  todo.done
                    ? 'border-orange-500 bg-orange-500'
                    : 'border-orange-300 hover:border-orange-400'
                }`}
              >
                {todo.done && <CheckIcon />}
              </button>
              <span
                className={`text-base ${
                  todo.done ? 'text-gray-400 line-through' : 'text-gray-700'
                }`}
              >
                {todo.text}
              </span>
            </div>
          ))
        )}
      </div>

      <div className="border-t border-gray-100 px-5 py-3">
        <form
          onSubmit={(e) => {
            e.preventDefault();
            addTodo();
          }}
          className="flex items-center gap-2"
        >
          <input
            ref={inputRef}
            type="text"
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder="What needs to be done?"
            className="flex-1 rounded-lg bg-gray-50 px-3 py-2.5 text-base text-gray-700 placeholder-gray-300 focus:outline-none"
          />
          <button
            type="submit"
            className="rounded-lg bg-orange-500 px-4 py-2.5 text-sm font-semibold text-white hover:bg-orange-600"
          >
            Add
          </button>
        </form>
      </div>
    </div>
  );
}
